//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngenicoPOSAPITest.MiddlewareServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TerminalStatusInfo", Namespace="http://schemas.datacontract.org/2004/07/Ingenico.Middleware.Model")]
    [System.SerializableAttribute()]
    public partial class TerminalStatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal lastTransactionAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastTransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastTransactionResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IngenicoPOSAPITest.MiddlewareServiceReference.MiddlewareAckCode middlewareAckCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte reversalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string softwareVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string terminalStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PosErrorCode {
            get {
                return this.PosErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PosErrorCodeField, value) != true)) {
                    this.PosErrorCodeField = value;
                    this.RaisePropertyChanged("PosErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal lastTransactionAmount {
            get {
                return this.lastTransactionAmountField;
            }
            set {
                if ((this.lastTransactionAmountField.Equals(value) != true)) {
                    this.lastTransactionAmountField = value;
                    this.RaisePropertyChanged("lastTransactionAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastTransactionId {
            get {
                return this.lastTransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.lastTransactionIdField, value) != true)) {
                    this.lastTransactionIdField = value;
                    this.RaisePropertyChanged("lastTransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastTransactionResponseCode {
            get {
                return this.lastTransactionResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.lastTransactionResponseCodeField, value) != true)) {
                    this.lastTransactionResponseCodeField = value;
                    this.RaisePropertyChanged("lastTransactionResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IngenicoPOSAPITest.MiddlewareServiceReference.MiddlewareAckCode middlewareAckCode {
            get {
                return this.middlewareAckCodeField;
            }
            set {
                if ((this.middlewareAckCodeField.Equals(value) != true)) {
                    this.middlewareAckCodeField = value;
                    this.RaisePropertyChanged("middlewareAckCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte reversalStatus {
            get {
                return this.reversalStatusField;
            }
            set {
                if ((this.reversalStatusField.Equals(value) != true)) {
                    this.reversalStatusField = value;
                    this.RaisePropertyChanged("reversalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string softwareVersion {
            get {
                return this.softwareVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.softwareVersionField, value) != true)) {
                    this.softwareVersionField = value;
                    this.RaisePropertyChanged("softwareVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string terminalStatus {
            get {
                return this.terminalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.terminalStatusField, value) != true)) {
                    this.terminalStatusField = value;
                    this.RaisePropertyChanged("terminalStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiddlewareAckCode", Namespace="http://schemas.datacontract.org/2004/07/Ingenico.Middleware.Utility")]
    public enum MiddlewareAckCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeOut = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SyntaxError = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MiddlewareIOError = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MiddlewareIsBusyForOtherRequest = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreviousRequestIsCanceled = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MiddlewareGeneralError = 96,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportRequestType", Namespace="http://schemas.datacontract.org/2004/07/Ingenico.Middleware.Utility")]
    public enum ReportRequestType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMVReport = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SettlementReport = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchReport = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReversalReport = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastTransaction = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionInfo", Namespace="http://schemas.datacontract.org/2004/07/Ingenico.Middleware.Model")]
    [System.SerializableAttribute()]
    public partial class TransactionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string privateDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal transactionAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.invoiceNumberField, value) != true)) {
                    this.invoiceNumberField = value;
                    this.RaisePropertyChanged("invoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string privateData {
            get {
                return this.privateDataField;
            }
            set {
                if ((object.ReferenceEquals(this.privateDataField, value) != true)) {
                    this.privateDataField = value;
                    this.RaisePropertyChanged("privateData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal transactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                if ((this.transactionAmountField.Equals(value) != true)) {
                    this.transactionAmountField = value;
                    this.RaisePropertyChanged("transactionAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionIdField, value) != true)) {
                    this.transactionIdField = value;
                    this.RaisePropertyChanged("transactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionTypeField, value) != true)) {
                    this.transactionTypeField = value;
                    this.RaisePropertyChanged("transactionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TxnResponseInfo", Namespace="http://schemas.datacontract.org/2004/07/Ingenico.Middleware.Model")]
    [System.SerializableAttribute()]
    public partial class TxnResponseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorizationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IngenicoPOSAPITest.MiddlewareServiceReference.TransactionInfo DebitRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IngenicoPOSAPITest.MiddlewareServiceReference.txnResponseEntryMode EntryModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssuerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetrivalReferenceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalVerificationResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionCertificateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionStatusInformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationIdentifier {
            get {
                return this.ApplicationIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationIdentifierField, value) != true)) {
                    this.ApplicationIdentifierField = value;
                    this.RaisePropertyChanged("ApplicationIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorizationCode {
            get {
                return this.AuthorizationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorizationCodeField, value) != true)) {
                    this.AuthorizationCodeField = value;
                    this.RaisePropertyChanged("AuthorizationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchNumber {
            get {
                return this.BatchNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchNumberField, value) != true)) {
                    this.BatchNumberField = value;
                    this.RaisePropertyChanged("BatchNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IngenicoPOSAPITest.MiddlewareServiceReference.TransactionInfo DebitRequest {
            get {
                return this.DebitRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitRequestField, value) != true)) {
                    this.DebitRequestField = value;
                    this.RaisePropertyChanged("DebitRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IngenicoPOSAPITest.MiddlewareServiceReference.txnResponseEntryMode EntryMode {
            get {
                return this.EntryModeField;
            }
            set {
                if ((this.EntryModeField.Equals(value) != true)) {
                    this.EntryModeField = value;
                    this.RaisePropertyChanged("EntryMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuerName {
            get {
                return this.IssuerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuerNameField, value) != true)) {
                    this.IssuerNameField = value;
                    this.RaisePropertyChanged("IssuerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantID {
            get {
                return this.MerchantIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantIDField, value) != true)) {
                    this.MerchantIDField = value;
                    this.RaisePropertyChanged("MerchantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetrivalReferenceNo {
            get {
                return this.RetrivalReferenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RetrivalReferenceNoField, value) != true)) {
                    this.RetrivalReferenceNoField = value;
                    this.RaisePropertyChanged("RetrivalReferenceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalID {
            get {
                return this.TerminalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalIDField, value) != true)) {
                    this.TerminalIDField = value;
                    this.RaisePropertyChanged("TerminalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalVerificationResult {
            get {
                return this.TerminalVerificationResultField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalVerificationResultField, value) != true)) {
                    this.TerminalVerificationResultField = value;
                    this.RaisePropertyChanged("TerminalVerificationResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCertificate {
            get {
                return this.TransactionCertificateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionCertificateField, value) != true)) {
                    this.TransactionCertificateField = value;
                    this.RaisePropertyChanged("TransactionCertificate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((this.TransactionDateField.Equals(value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionStatusInformation {
            get {
                return this.TransactionStatusInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionStatusInformationField, value) != true)) {
                    this.TransactionStatusInformationField = value;
                    this.RaisePropertyChanged("TransactionStatusInformation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="txnResponseEntryMode", Namespace="http://schemas.datacontract.org/2004/07/Ingenico.Middleware.Utility")]
    public enum txnResponseEntryMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mag = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMVChip = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeyEntry = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fallback = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NA = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportResultInfo", Namespace="http://schemas.datacontract.org/2004/07/Ingenico.Middleware.Model")]
    [System.SerializableAttribute()]
    public partial class ReportResultInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IngenicoPOSAPITest.MiddlewareServiceReference.MiddlewareAckCode middlewareAckCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reportDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int flag {
            get {
                return this.flagField;
            }
            set {
                if ((this.flagField.Equals(value) != true)) {
                    this.flagField = value;
                    this.RaisePropertyChanged("flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IngenicoPOSAPITest.MiddlewareServiceReference.MiddlewareAckCode middlewareAckCode {
            get {
                return this.middlewareAckCodeField;
            }
            set {
                if ((this.middlewareAckCodeField.Equals(value) != true)) {
                    this.middlewareAckCodeField = value;
                    this.RaisePropertyChanged("middlewareAckCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reportData {
            get {
                return this.reportDataField;
            }
            set {
                if ((object.ReferenceEquals(this.reportDataField, value) != true)) {
                    this.reportDataField = value;
                    this.RaisePropertyChanged("reportData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiddlewareServiceReference.IMiddlewareService", CallbackContract=typeof(IngenicoPOSAPITest.MiddlewareServiceReference.IMiddlewareServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMiddlewareService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMiddlewareService/WaitTransactionResponse")]
        void WaitTransactionResponse(int timeOut);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMiddlewareService/WaitTransactionResponse")]
        System.Threading.Tasks.Task WaitTransactionResponseAsync(int timeOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiddlewareService/Init", ReplyAction="http://tempuri.org/IMiddlewareService/InitResponse")]
        int Init(string message, int displayTimeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiddlewareService/Init", ReplyAction="http://tempuri.org/IMiddlewareService/InitResponse")]
        System.Threading.Tasks.Task<int> InitAsync(string message, int displayTimeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiddlewareService/Poll", ReplyAction="http://tempuri.org/IMiddlewareService/PollResponse")]
        int Poll(int polingType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiddlewareService/Poll", ReplyAction="http://tempuri.org/IMiddlewareService/PollResponse")]
        System.Threading.Tasks.Task<int> PollAsync(int polingType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMiddlewareService/WaitTerminalStatus")]
        void WaitTerminalStatus(int timeOut);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMiddlewareService/WaitTerminalStatus")]
        System.Threading.Tasks.Task WaitTerminalStatusAsync(int timeOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiddlewareService/TerminalStatus", ReplyAction="http://tempuri.org/IMiddlewareService/TerminalStatusResponse")]
        IngenicoPOSAPITest.MiddlewareServiceReference.TerminalStatusInfo TerminalStatus(int statusType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiddlewareService/TerminalStatus", ReplyAction="http://tempuri.org/IMiddlewareService/TerminalStatusResponse")]
        System.Threading.Tasks.Task<IngenicoPOSAPITest.MiddlewareServiceReference.TerminalStatusInfo> TerminalStatusAsync(int statusType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiddlewareService/ReportRequest", ReplyAction="http://tempuri.org/IMiddlewareService/ReportRequestResponse")]
        int ReportRequest(IngenicoPOSAPITest.MiddlewareServiceReference.ReportRequestType reportRequestType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiddlewareService/ReportRequest", ReplyAction="http://tempuri.org/IMiddlewareService/ReportRequestResponse")]
        System.Threading.Tasks.Task<int> ReportRequestAsync(IngenicoPOSAPITest.MiddlewareServiceReference.ReportRequestType reportRequestType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMiddlewareService/WaitReportRequest")]
        void WaitReportRequest(int timeOut);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMiddlewareService/WaitReportRequest")]
        System.Threading.Tasks.Task WaitReportRequestAsync(int timeOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiddlewareService/TransactionRequest", ReplyAction="http://tempuri.org/IMiddlewareService/TransactionRequestResponse")]
        int TransactionRequest(IngenicoPOSAPITest.MiddlewareServiceReference.TransactionInfo transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiddlewareService/TransactionRequest", ReplyAction="http://tempuri.org/IMiddlewareService/TransactionRequestResponse")]
        System.Threading.Tasks.Task<int> TransactionRequestAsync(IngenicoPOSAPITest.MiddlewareServiceReference.TransactionInfo transaction);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiddlewareServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMiddlewareService/TransactionResponse")]
        void TransactionResponse(IngenicoPOSAPITest.MiddlewareServiceReference.TxnResponseInfo txnResponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMiddlewareService/ReturnTerminalStatus")]
        void ReturnTerminalStatus(IngenicoPOSAPITest.MiddlewareServiceReference.TerminalStatusInfo terminalStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMiddlewareService/ReportResult")]
        void ReportResult([System.ServiceModel.MessageParameterAttribute(Name="reportResult")] IngenicoPOSAPITest.MiddlewareServiceReference.ReportResultInfo reportResult1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiddlewareServiceChannel : IngenicoPOSAPITest.MiddlewareServiceReference.IMiddlewareService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiddlewareServiceClient : System.ServiceModel.DuplexClientBase<IngenicoPOSAPITest.MiddlewareServiceReference.IMiddlewareService>, IngenicoPOSAPITest.MiddlewareServiceReference.IMiddlewareService {
        
        public MiddlewareServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MiddlewareServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MiddlewareServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MiddlewareServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MiddlewareServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void WaitTransactionResponse(int timeOut) {
            base.Channel.WaitTransactionResponse(timeOut);
        }
        
        public System.Threading.Tasks.Task WaitTransactionResponseAsync(int timeOut) {
            return base.Channel.WaitTransactionResponseAsync(timeOut);
        }
        
        public int Init(string message, int displayTimeout) {
            return base.Channel.Init(message, displayTimeout);
        }
        
        public System.Threading.Tasks.Task<int> InitAsync(string message, int displayTimeout) {
            return base.Channel.InitAsync(message, displayTimeout);
        }
        
        public int Poll(int polingType) {
            return base.Channel.Poll(polingType);
        }
        
        public System.Threading.Tasks.Task<int> PollAsync(int polingType) {
            return base.Channel.PollAsync(polingType);
        }
        
        public void WaitTerminalStatus(int timeOut) {
            base.Channel.WaitTerminalStatus(timeOut);
        }
        
        public System.Threading.Tasks.Task WaitTerminalStatusAsync(int timeOut) {
            return base.Channel.WaitTerminalStatusAsync(timeOut);
        }
        
        public IngenicoPOSAPITest.MiddlewareServiceReference.TerminalStatusInfo TerminalStatus(int statusType) {
            return base.Channel.TerminalStatus(statusType);
        }
        
        public System.Threading.Tasks.Task<IngenicoPOSAPITest.MiddlewareServiceReference.TerminalStatusInfo> TerminalStatusAsync(int statusType) {
            return base.Channel.TerminalStatusAsync(statusType);
        }
        
        public int ReportRequest(IngenicoPOSAPITest.MiddlewareServiceReference.ReportRequestType reportRequestType) {
            return base.Channel.ReportRequest(reportRequestType);
        }
        
        public System.Threading.Tasks.Task<int> ReportRequestAsync(IngenicoPOSAPITest.MiddlewareServiceReference.ReportRequestType reportRequestType) {
            return base.Channel.ReportRequestAsync(reportRequestType);
        }
        
        public void WaitReportRequest(int timeOut) {
            base.Channel.WaitReportRequest(timeOut);
        }
        
        public System.Threading.Tasks.Task WaitReportRequestAsync(int timeOut) {
            return base.Channel.WaitReportRequestAsync(timeOut);
        }
        
        public int TransactionRequest(IngenicoPOSAPITest.MiddlewareServiceReference.TransactionInfo transaction) {
            return base.Channel.TransactionRequest(transaction);
        }
        
        public System.Threading.Tasks.Task<int> TransactionRequestAsync(IngenicoPOSAPITest.MiddlewareServiceReference.TransactionInfo transaction) {
            return base.Channel.TransactionRequestAsync(transaction);
        }
    }
}
